# Generated by Django 5.1.2 on 2024-12-01 10:02

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
