# Generated by Django 5.1.2 on 2024-12-01 10:20

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_vector',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, editable=False, null=True),
        ),
    ]
