# Generated by Django 5.1.2 on 2024-10-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="ocr_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/ocr/"),
        ),
        migrations.AddField(
            model_name="pdf",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
    ]
