# Generated by Django 5.1.2 on 2024-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_pdf_ocr_file_pdf_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
