# Generated by Django 5.1.2 on 2024-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_pdf_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
