# Generated by Django 5.1.2 on 2024-12-01 10:34

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_document_file_alter_document_ocr_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_vector',
            field=pgvector.django.VectorField(blank=True, dimensions=3072, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['embedding_vector'], name='vector_index'),
        ),
    ]
