# Generated by Django 5.1.2 on 2024-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_documentchunk_embedding_vector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['document', 'index']},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='app_documen_status_24163e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='app_documen_created_da0f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'index'], name='app_documen_documen_c8657e_idx'),
        ),
    ]
