# Generated by Django 5.1.2 on 2024-12-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_documentchunk_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='vector_index',
        ),
    ]
