# Generated by Django 5.1.2 on 2024-12-14 14:46

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_documentchunk_embedding_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.HnswIndex(ef_construction=128, fields=['embedding_vector'], m=16, name='embedding_vector_index', opclasses=['vector_cosine_ops']),
        ),
    ]
