# Generated by Django 5.1.2 on 2024-12-17 05:30

import app.constant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_documentchunk_embedding_vector_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='app_documen_documen_c8657e_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default=app.constant.DocumentStatus['PENDING'], max_length=100),
        ),
    ]
