# Generated by Django 5.1.2 on 2024-12-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_documentchunk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
