# Generated by Django 5.1.2 on 2024-12-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_document_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
